### ISSUE TITLE
calibration.tar.gz.torrent no available

### ISSUE THREAD

**Issue by robert12321** [antorsae/didi-competition#1]
Hello,
I'm writing a bachalor thesis about obstacle detection. I would like to run your code. However I cannot download  calibration data. Could you share calibration.tar.gz ? Torrent doesn't work, because no seeders.
I would appreciate your help.
Thank you in advance
Regards
Robert Czwartosz

**Comment by antorsae** [comment]
Hi Robert, unfortunately I longer have it.

**Comment by robert12321** [comment]
Could you advice me how to recreate this data?

**Comment by robert12321** [comment]
@drummist180 in other issue ([https://github.com/udacity/didi-competition/issues/15](url)) commented: " There were reports during the competition that the calibration data may have been incorrect or lacking necessary information. So even if you find it, it might not be very useful. If you have forum access, here's one such report:
[https://discussions.udacity.com/t/calibration-matrix-to-project-lidar-points-onto-camera-image/250099](url) "

Closing the issue.
